services:
  postgres:
    image: postgres:16
    container_name: pg-notifications
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications_db
    ports:
      - "5432:5432"
    restart: unless-stopped